version: '3.8'

services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    env_file: ./.env

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    env_file: ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    restart: always
    env_file: ./.env
    command: server --console-address ":9006" --address ":9000" /data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9006"
    volumes:
      - minio_data:/data

  captcha:
    build:
      context: ./captcha-lab
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - CAPTCHA_TIMEOUT=${CAPTCHA_TIMEOUT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MINIO_HOST=minio
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - CAPTCHA_SERVICE_URL=http://captcha:8080
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - mysql
      - minio
      - captcha
    restart: always
    volumes:
      - tiles:/usr/src/app/tiles
      - logs:/usr/src/app/log

volumes:
  redis_data:
  mysql_data:
  minio_data:
  tiles:
  logs: